FROM mcr.microsoft.com/dotnet/sdk:7.0 AS db-builder
WORKDIR /app
COPY ./src/TopicManagementService.Database ./TopicManagementService.Database
RUN dotnet build ./TopicManagementService.Database/TopicManagementService.Database.csproj

FROM mcr.microsoft.com/mssql/server:2022-latest AS sql-server
USER root
RUN apt-get update && \
    apt-get install -y unzip curl libunwind8 libicu66 && \
    curl -L https://aka.ms/sqlpackage-linux -o sqlpackage.zip && \
    unzip sqlpackage.zip -d /opt/sqlpackage && \
    chmod +x /opt/sqlpackage/sqlpackage && \
    ln -s /opt/sqlpackage/sqlpackage /usr/local/bin/sqlpackage && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* sqlpackage.zip /tmp/* /var/tmp/*
USER mssql

COPY --from=db-builder ./app/TopicManagementService.Database/bin/Debug/netstandard2.0/TopicManagementService.Database.dacpac /deploy/TopicManagementService.Database.dacpac
COPY ./deploy/docker/standalone/db/db-entrypoint.sh /deploy/db-entrypoint.sh